def printeos(EOS):
    print "GPS Information Found"
    print str(EOS.LAT) + " Latitude"
    print str(EOS.LONG) + " Longitude"
    print str(EOS.SOG) + " Speed Over Ground"
    print str(EOS.COG) + " Course Over Ground"
    print EOS.UTC + " GPS Unformated Time"       

    print "Sent Sentance 0"
    print str(EOS.Hours) + " Hours"
    print str(EOS.Minutes) + " Minutes"
    print str(EOS.Seconds ) + " Seconds"
    print str(EOS.Day) + " Day"
    print str(EOS.Month) + " Month"
    print str(EOS.Year) + " Year"
    print "Sent Sentence 1"
    print str(EOS.WindSpeed) + " Wind Speed"
    print str(EOS.High_Gust) + " High Gust"
    print str(EOS.WindSpeed_Avg) + " Wind Speed Average"
    print str(EOS.Wind_UoM) + " Wind UoM"
    print str(EOS.WindDirection) + " Wind Direction"
    print "Saved Sentence 2"
    print str(EOS.Pressure_Abs) + " Pressure Absolute"
    print str(EOS.Pressure_Rel) + " Pressure Relative"
    print str(EOS.Altitude) + " Altitude"
    print str(EOS.Pressure_Trend) + " Pressure Trend"
    print "Sent Sentence 3"
    print str(EOS.Temp_Outside) + " Temp Outside"
    print str(EOS.Temp_DewPoint) + " Temp Dew Point"
    print str(EOS.Humidity_Rel) + " Relative Humidity"
    print str(EOS.Temp_Trend) + " Temp Trend"
    print str(EOS.Temp_UoM) + " Temp UoM"
    print "Sent Sentence 4"
    print str(EOS.Rain_Rate) + " Rain Rate"
    print str(EOS.Rain_Amount) + " Rain Amount"
    print str(EOS.Rain_FallToday) + " Rain Today"
    print str(EOS.Rain_FallYesterday) + " Rain Yesterday"
    print str(EOS.Rain_Rate_UoM) + " Rain UoM"
    print str(EOS.Rain_Tips) + " Rain Tips"       
    print "Sent Sentence 5"
    print str(EOS.Solar_Lum) + " Solar Lum"
    print str(EOS.Solar_UV) + " Solar UV"
    print str(EOS.Solar_Rad) + " Solar Radiation"
    print str(EOS.Solar_RadHi) + " Solar Radiation High"
    print str(EOS.Solar_Energy) + " Solar_Energy"
    print "Sent Sentence 6"
    print str(EOS.B_Volts) + " Battery Voltage"
    print str(EOS.C_Temp) + " Cabin Temp"

